// channel_name只是編輯時確認用
// 不另外放json檔是想要寫註解
const channelList = [
    { "channel_id": "UCD-miitqNY3nyukJ4Fnf4_A", "channel_name": "月ノ美兎", "color": "#E43F3B" },
    { "channel_id": "UCLO9QDxVL4bnvRRsz6K4bsQ", "channel_name": "勇気ちひろ", "color": "#7BB3EE" },
    { "channel_id": "UCYKP16oMX9KKPbrNgo_Kgag", "channel_name": "える / Elu【にじさんじ】", "color": "#E2364F" },
    { "channel_id": "UCsg-YqdqQ-KFF0LNk23BY4A", "channel_name": "樋口楓【にじさんじ所属】", "color": "#FBAF71" },
    { "channel_id": "UC6oDys1BGgBsIC3WhG1BovQ", "channel_name": "Shizuka Rin Official", "color": "#745399" },
    { "channel_id": "UCeK9HFcRZoTrvqcUCtccMoQ", "channel_name": "渋谷ハジメのはじめ支部", "color": "#D7FAD7" },
    { "channel_id": "UCpnvhOIJ6BN-vPkYU9ls-Eg", "channel_name": "鈴谷アキの陽だまりの庭", "color": "#F2F9C3" },
    { "channel_id": "UCvmppcdYf4HOv-tFQhHHJMA", "channel_name": "《にじさんじ所属の女神》モイラ", "color": "#91ABD0" },
    //
    { "channel_id": "UCwokZsOK_uEre70XayaFnzA", "channel_name": "鈴鹿詩子 Utako Suzuka", "color": "#FA4F62" },
    { "channel_id": "UCmUjjW5zF1MMOhYUwwwQv9Q", "channel_name": "宇志海いちご", "color": "#FFCACE" },
    { "channel_id": "UC_GCs6GARLxEHxy1w40d6VQ", "channel_name": "家長むぎ【にじさんじ所属】", "color": "#FF899D" },
    { "channel_id": "UC48jH1ul-6HOrcSSfoR02fQ", "channel_name": "Yuhi Riri Official", "color": "#BFFFFF" },
    { "channel_id": "UCt0clH12Xk1-Ej5PXKGfdPA", "channel_name": "♥️♠️物述有栖♦️♣️", "color": "#81D4E2" },
    { "channel_id": "UCBiqkFJljoxAj10SoP2w2Cg", "channel_name": "文野環【にじさんじの野良猫】ふみのたまき", "color": "#EBDDB4" },
    { "channel_id": "UCXU7YYxy_iQd3ulXyO-zC2w", "channel_name": "伏見ガク【にじさんじ所属】", "color": "#FFCB5B" },
    { "channel_id": "UCUzJ90o1EjqUbk2pBAy0_aw", "channel_name": "Gilzaren III Season 2", "color": "#002FA7" },
    { "channel_id": "UCv1fFr156jc65EMiLbaLImw", "channel_name": "剣持刀也", "color": "#A590AF" },
    { "channel_id": "UCtpB6Bvhs1Um93ziEDACQ8g", "channel_name": "森中花咲", "color": "#C8F39A" },
    //
    { "channel_id": "UCspv01oxUFf_MTSipURRhkA", "channel_name": "Kanae Channel", "color": "#ABD3D8" },
    { "channel_id": "UCBi8YaVyZpiKWN3_Z0dCTfQ", "channel_name": "赤羽葉子ちゃんねる", "color": "#CA636C" },
    { "channel_id": "UCoztvTULBYd3WmStqYeoHcA", "channel_name": "笹木咲 / Sasaki Saku", "color": "#EF9AAF" },
    { "channel_id": "UC0g1AE0DOjBYnLhkgoRWN1w", "channel_name": "本間ひまわり - Himawari Honma -", "color": "#FBE340" },
    { "channel_id": "UC9EjSJ8pvxtvPdxLOElv73w", "channel_name": "魔界ノりりむ", "color": "#EF6F94" },
    { "channel_id": "UCSFCh5NL4qXrAy9u-u2lX3g", "channel_name": "Kuzuha Channel", "color": "#ACA7BB" },
    { "channel_id": "UC_4tXjqecqox5Uc05ncxpxg", "channel_name": "椎名唯華 / Shiina Yuika", "color": "#F1C8DE" },
    //
    { "channel_id": "UC53UDnhAAYwvNO7j_2Ju1cQ", "channel_name": "ドーラ", "color": "#A83E4A" },
    { "channel_id": "UCRV9d6YCYIMUszK-83TwxVA", "channel_name": "轟京子/kyoko todoroki【にじさんじ】", "color": "#F8A69A" },
    { "channel_id": "UC1zFJrfEKvCixhsjNSb1toQ", "channel_name": "シスター・クレア -SisterClaire-", "color": "#DFC6A8" },
    { "channel_id": "UCsFn_ueskBkMCEyzCEqAOvg", "channel_name": "花畑チャイカ", "color": "#40CF84" },
    { "channel_id": "UCKMYISTJAQ8xTplUPHiABlA", "channel_name": "社築", "color": "#B6C6F2" },
    { "channel_id": "UC6TfqY40Xt1Y0J-N18c85qQ", "channel_name": "安土桃", "color": "#F295CE" },
    { "channel_id": "UCryOPk2GZ1meIDt53tL30Tw", "channel_name": "鈴木勝 / Suzuki Masaru【にじさんじ】", "color": "#7B788A" },
    { "channel_id": "UCt5-0i4AVHXaWJrL8Wql3mw", "channel_name": "緑仙 / Ryushen", "color": "#5DCCAB" },
    { "channel_id": "UC3lNFeJiTq6L3UWoz4g1e-A", "channel_name": "卯月コウ", "color": "#F9E97A" },
    //
    { "channel_id": "UCWz0CSYCxf4MhRKPDm220AQ", "channel_name": "神田笑一 / Kanda Shoichi【 にじさんじ 】", "color": "#F4D35B" },
    { "channel_id": "UCiSRx1a2k-0tOg-fs6gAolQ", "channel_name": "飛鳥ひな【にじさんじ所属】", "color": "#FAD8DC" },
    { "channel_id": "UCtAvQ5U0aXyKwm2i4GqFgJg", "channel_name": "春崎エアル", "color": "#4B5F9E" },
    { "channel_id": "UCRWOdwLRsenx2jLaiCAIU4A", "channel_name": "雨森小夜", "color": "#756F7D" },
    { "channel_id": "UCV5ZZlLjk5MKGg3L0n0vbzw", "channel_name": "鷹宮リオン / Rion Takamiya", "color": "#CC3D7B" },
    { "channel_id": "UCJubINhCcFXlsBwnHp0wl_g", "channel_name": "舞元啓介", "color": "#094078" },
    { "channel_id": "UCPvGypSgfDkVe7JG2KygK7A", "channel_name": "竜胆 尊 / Rindou Mikoto", "color": "#745BFF" },
    { "channel_id": "UCjlmCrq4TP1I4xguOtJ-31w", "channel_name": "でびでび・でびる", "color": "#444C7D" },
    { "channel_id": "UCfQVs_KuXeNAlGa3fb8rlnQ", "channel_name": "桜凛月", "color": "#C57FC7" },
    { "channel_id": "UCo7TRj3cS-f_1D9ZDmuTsjw", "channel_name": "町田ちま【にじさんじ】", "color": "#EDDDBB" },
    { "channel_id": "UChUJbHiTVeGrSkTdBzVfNCQ", "channel_name": "ジョー・力一 Joe Rikiichi", "color": "#D598DD" },
    { "channel_id": "UCoM_XmK45j504hfUWvN06Qg", "channel_name": "成瀬 鳴 / Naruse Naru【にじさんじ】", "color": "#E06489" },
    { "channel_id": "UCbc8fwhdUNlqi-J99ISYu4A", "channel_name": "ベルモンド・バンデラス", "color": "#683D46" },
    { "channel_id": "UCvzVB-EYuHFXHZrObB8a_Og", "channel_name": "矢車りね - Rine Yaguruma -", "color": "#FEECD8" },
    { "channel_id": "UCTIE7LM5X15NVugV7Krp9Hw", "channel_name": "夢追翔のJUKE BOX", "color": "#AC324B" },
    { "channel_id": "UCmeyo5pRj_6PXG-CsGUuWWg", "channel_name": "黒井しば【にじさんじの犬】", "color": "#585C82s" },
    //
    { "channel_id": "UCeShTCVgZyq2lsBW9QwIJcw", "channel_name": "【3年0組】郡道美玲の教室", "color": "#A20063" },
    { "channel_id": "UCCVwhI5trmaSxfcze_Ovzfw", "channel_name": "夢月ロア🌖Yuzuki Roa", "color": "#D8368D" },
    { "channel_id": "UCg63a3lk6PNeWhVvMRM_mrQ", "channel_name": "小野町 春香 / Onomachi Haruka 【にじさんじ】", "color": "#FF336E" },
    { "channel_id": "UCufQu4q65z63IgE4cfKs1BQ", "channel_name": "語部紡", "color": "#07A4E3" },
    { "channel_id": "UCHK5wkevfaGrPr7j3g56Jmw", "channel_name": "瀬戸 美夜子 - Miyako Seto", "color": "#C4FF2B" },
    { "channel_id": "UCXRlIK3Cw_TJIQC5kSJJQMg", "channel_name": "戌亥とこ -Inui Toko-", "color": "#9d3757" },
    { "channel_id": "UCHVXbQzkl3rDfsXWo8xi2qw", "channel_name": "アンジュ・カトリーナ - Ange Katrina -", "color": "#C83C35" },
    { "channel_id": "UCZ1xuCK1kNmn5RzPYIZop3w", "channel_name": "リゼ・ヘルエスタ -Lize Helesta-", "color": "#42FFFF" },
    //
    { "channel_id": "UCNW1Ex0r6HsWRD4LCtPwvoQ", "channel_name": "三枝明那 / Saegusa Akina", "color": "#F03C31" },
    { "channel_id": "UC0WwEfE-jOM2rzjpdfhTzZA", "channel_name": "愛園 愛美/Aizono Manami", "color": "#F98FB7" },
    { "channel_id": "UCHX7YpFG8rVwhsHCx34xt7w", "channel_name": "雪城眞尋/Yukishiro Mahiro【にじさんじ所属】", "color": "#B4E9FF" },
    { "channel_id": "UCIytNcoz4pWzXfLda0DoULQ", "channel_name": "エクス・アルビオ -Ex Albio-", "color": "#5C9BBC" },
    { "channel_id": "UCtnO2N4kPTXmyvedjGWdx3Q", "channel_name": "レヴィ・エリファ-Levi Elipha- ", "color": "#E8E1E8" },
    { "channel_id": "UCfipDDn7wY-C-SoUChgxCQQ", "channel_name": "葉山舞鈴 / Ohayama Ch.", "color": "#D9EC33" },
    { "channel_id": "UCUc8GZfFxtmk7ZwSO7ccQ0g", "channel_name": "ニュイ・ソシエール //[Nui Sociere]", "color": "#D24E5F" },
    //
    { "channel_id": "UCGYAYLDE7TZiiC8U6teciDQ", "channel_name": "葉加瀬 冬雪 / Hakase Fuyuki", "color": "#EEFFFF" },
    { "channel_id": "UCmovZ2th3Sqpd00F5RdeigQ", "channel_name": "加賀美 ハヤト/Hayato Kagami", "color": "#B9ADB9" },
    { "channel_id": "UCL34fAoFim9oHLbVzMKFavQ", "channel_name": "夜見れな/yorumi rena【にじさんじ所属】", "color": "#F7265A" },
    { "channel_id": "UCb5JxV6vKlYVknoJB8TnyYg", "channel_name": "黛 灰 / Kai Mayuzumi【にじさんじ】", "color": "#086776" },
    { "channel_id": "UCdpUojq0KWZCN9bxXnZwz5w", "channel_name": "アルス・アルマル -ars almal- 【にじさんじ】", "color": "#7FD6E2" },
    { "channel_id": "UCnRQYHTnRLSF0cLJwMnedCg", "channel_name": "相羽ういは〖Aiba Uiha〗にじさんじ所属", "color": "#324CAC" },
    { "channel_id": "UCkIimWZ9gBJRamKF0rmPU8w", "channel_name": "天宮 こころ / Amamya Ch.", "color": "#C5EDFF" },
    { "channel_id": "UCpNH2Zk2gw3JBjWAKSyZcQQ", "channel_name": "エリー・コニファー / Eli Conifer【にじさんじ】", "color": "#DAFFF9" },
    { "channel_id": "UCIG9rDtgR45VCZmYnd-4DUw", "channel_name": "ラトナ・プティ -Ratna Petit -にじさんじ所属", "color": "#F8B759" },
    { "channel_id": "UC2OacIzd2UxGHRGhdHl1Rhw", "channel_name": "早瀬 走 / Hayase Sou【にじさんじ所属】", "color": "#AA7BE8" },
    { "channel_id": "UC8C1LLhBhf_E2IBPLSDJXlQ", "channel_name": "健屋花那【にじさんじ】KanaSukoya", "color": "#FF2FA2" },
    { "channel_id": "UCHBhnG2G-qN0JrrWmMO2FTA", "channel_name": "シェリン・バーガンディ -Shellin Burgundy- 【にじさんじ】", "color": "#6C2735" },
    //
    { "channel_id": "UCwrjITPwG4q71HzihV2C7Nw", "channel_name": "フミ/にじさんじ", "color": "#F4E49D" },
    { "channel_id": "UC9V3Y3_uzU5e-usObb6IE1w", "channel_name": "星川サラ / Sara Hoshikawa", "color": "#FAB80D" },
    { "channel_id": "UCllKI7VjyANuS1RXatizfLQ", "channel_name": "山神 カルタ / Karuta Yamagami", "color": "#384B5A" },
    { "channel_id": "UCl1oLKcAq93p-pwKfDGhiYQ", "channel_name": "えま★おうがすと / Emma★August【にじさんじ】", "color": "#B32F51" },
    { "channel_id": "UCb6ObE-XGCctO3WrjRZC-cw", "channel_name": "ルイス・キャミー", "color": "#E86A74" },
    { "channel_id": "UCerkculBD7YLc_vOGrF7tKg", "channel_name": "魔使マオ -matsukai mao-", "color": "#C93965" },
    { "channel_id": "UC6wvdADTJ88OfIbJYIpAaDA", "channel_name": "不破 湊 / Fuwa Minato【にじさんじ】", "color": "#BF69F4" },
    { "channel_id": "UCuvk5PilcvDECU7dDZhQiEw", "channel_name": "白雪 巴/Shirayuki Tomoe", "color": "#6E3FE7" },
    { "channel_id": "UC1QgXt46-GEvtNjEC1paHnw", "channel_name": "グウェル・オス・ガール / Gwelu Os Gar 【にじさんじ】", "color": "#F04B2D" },
    { "channel_id": "UCfki3lMEF6SGBFiFfo9kvUA", "channel_name": "ましろ / Mashiro", "color": "#1E2232" },
    { "channel_id": "UC-o-E6I3IC2q8sAoAuM6Umg", "channel_name": "奈羅花 - Naraka -", "color": "#A02655" },
    { "channel_id": "UCRcLAVTbmx2-iNcXSsupdNA", "channel_name": "来栖 夏芽-kurusu natsume-【にじさんじ】", "color": "#880223" },
    //
    { "channel_id": "UCuep1JCrMvSxOGgGhBfJuYw", "channel_name": "フレン・E・ルスタリオ", "color": "#EC1D2F" },
    { "channel_id": "UCmZ1Rbthn-6Jm_qOGjYsh5A", "channel_name": "イブラヒム【にじさんじ】", "color": "#7CA1F0" },
    { "channel_id": "UCXW4MqCQn-jCaxlX-nn-BYg", "channel_name": "長尾 景 / Nagao Kei【にじさんじ】", "color": "#625DA1" },
    { "channel_id": "UCGw7lrT-rVZCWHfdG9Frcgg", "channel_name": "弦月 藤士郎 / Genzuki Tojiro【にじさんじ】", "color": "#487591" },
    { "channel_id": "UCo2N7C-Z91waaR6lF3LL_jw", "channel_name": "甲斐田 晴 / Kaida Haru【にじさんじ】", "color": "#4DD7E3" },
    { "channel_id": "UC_82HBGtvwN1hcGeOGHzUBQ", "channel_name": "空星きらめ/Sorahoshi Kirame【にじさんじ】", "color": "#44DDF4" },
    { "channel_id": "UCe_p3YEuYJb8Np0Ip9dk-FQ", "channel_name": "朝日南アカネ / Asahina Akane 【にじさんじ】", "color": "#B7282E" },
    { "channel_id": "UCL_O_HXgLJx3Auteer0n0pA", "channel_name": "周央 サンゴ / Suo Sango【にじさんじ】", "color": "#EF8468" },
    { "channel_id": "UCebT4Aq-3XWb5je1S1FvR_A", "channel_name": "東堂コハク/ Todo Kohaku [にじさんじ]", "color": "#EA930A" },
    { "channel_id": "UCRqBKoKuX30ruKAq05pCeRQ", "channel_name": "北小路ヒスイ / Kitakoji Hisui 【にじさんじ】", "color": "#38B48B" },
    { "channel_id": "UCkngxfPbmGyGl_RIq4FA3MQ", "channel_name": "西園チグサ / Nishizono Chigusa", "color": "#3A8FB7" },
    //
    { "channel_id": "UC8oPnditPSp5lZu45fnXWCA", "channel_name": "アクシア・クローネ / Axia Krone 【にじさんじ】", "color": "#00A6FE" },
    { "channel_id": "UCgmFrRcyH7d1zR9sIVQhFow", "channel_name": "ローレン・イロアス / Lauren Iroas【にじさんじ】", "color": "#C10E49" },
    { "channel_id": "UC-6rZgmxZSIbq786j3RD5ow", "channel_name": "レオス・ヴィンセント / Leos.Vincent【にじさんじ】", "color": "#234A87" },
    { "channel_id": "UCqjTqdVlvIipZXIKeCkHKUA", "channel_name": "オリバー・エバンス / Oliver Evans 【にじさんじ】", "color": "#BCC37E" },
    { "channel_id": "UCRm6lqtdxs_Qo6HeL-SRQ-w", "channel_name": "レイン・パターソン／Lain Paterson【にじさんじ】", "color": "#F74848" },
    //
    { "channel_id": "UCAQDFeCTVdx90GtwohwjHzQ", "channel_name": "天ヶ瀬 むゆ / Amagase Muyu 【にじさんじ】", "color": "#FA5578" },
    { "channel_id": "UCe22Bcwd_GCpTjLxn83zl7A", "channel_name": "先斗寧 / Ponto Nei 【にじさんじ】", "color": "#5A7DFF" },
    { "channel_id": "UCtHY-tP0dyykhTRMmnfPs_g", "channel_name": "海妹四葉 / Umise Yotsuha 【にじさんじ】", "color": "#FFE632" },
    //
    { "channel_id": "UCgIfLpQvelloDi8I0Ycbwpg", "channel_name": "壱百満天原サロメ / Hyakumantenbara Salome", "color": "#CD3796" },
];

exports.channelList = channelList;

exports.getChannelIds = () => {
    return channelList.map((item) => item.channel_id)
}